name: Release Versioning

on:
  workflow_call:
    inputs:
      new_version:
        description: "The new version number to release"
        required: true
        type: string

permissions:
  contents: write

jobs:
  release-versioning:
    name: Release Versioning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0

      - name: Create tag
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ inputs.new_version }}',
              sha: context.sha
            })

      # - name: Download APK
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: android-${{ env.APPLICATION_NAME }}-${{ needs.generate-versioning.outputs.version }}
      #     path: dist/

      # - name: Download Web
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: web-${{ env.APPLICATION_NAME }}-${{ needs.generate-versioning.outputs.version }}
      #     path: dist/

      # - name: Create GitHub Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: ${{ inputs.new_version }}
      #     name: ${{ inputs.new_version }}
      #     prerelease: ${{ github.ref == 'refs/heads/main' }}
      #     # files: |
      #       # web-${{ env.APPLICATION_NAME }}-${{ needs.generate-versioning.outputs.version }}
      #       # android-${{ env.APPLICATION_NAME }}-${{ needs.generate-versioning.outputs.version }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}